language: cpp

python: 3.6

sudo: false

addons:
  apt:
    packages:
    # meson + ninja build system
    - ninja-build
    - ccache
    # Toolchain for compiling dependencies
    - autotools-dev
    - pkg-config
    - libtool
    # Dependencies
    - libboost-all-dev
    - libeigen3-dev

before_install:
- pip3.6 install --user meson

install:
- meson --wrap-mode=forcefallback src/builddir src
- ninja -C src/builddir

# Don't spam Prof. Lewis with testing a new build system <3
notifications:
  recipients:
    - omsai@member.fsf.org
  email:
    on_success: change
    on_failure: always
